.PHONY: build
build:
	dune build @install
	ln -sf _build/install/default/bin/exhausteve .

# Install build-time dependencies. Requires opam.
.PHONY: setup
setup:
	opam install --deps-only ./exhausteve.opam

.PHONY: test
test:
	dune build
	ln -sf _build/default/tests/test.exe test
	./test

.PHONY: demo
demo:
	echo '. | (..)* | (...)*' | ./exhausteve
	$(MAKE) graphs

# Check a regular expression that matches any string except "hello"
.PHONY: hello
hello:
	echo ".?.?.?.?|......+|[^h]....|.[^e]...|..[^l]..|...[^l].|....[^o]" \
	| ./exhausteve

# Render the graphs for the NFA and DFA generated by exhausteve.
#
# 'dot' is part of Graphviz.
.PHONY: graphs
graphs:
	dot -Tpng nfa.dot -o nfa.png
	dot -Tpng dfa.dot -o dfa.png
	xdg-open nfa.png &
	xdg-open dfa.png &

# For ocamllex experiments
.PHONY: export
export:
	./pack
