.PHONY: build
build:
	dune build @install

.PHONY: test
test:
	@echo "tests coming soon!"

.PHONY: demo
demo:
	echo ".?a*" | ./exhausteve
	$(MAKE) graphs

# Check a regular expression that matches any string except "hello"
.PHONY: hello
hello:
	echo ".?.?.?.?|......+|[^h]....|.[^e]...|..[^l]..|...[^l].|....[^o]" \
	| ./exhausteve

# Render the graphs for the NFA and DFA generated by exhausteve.
#
# 'dot' is part of Graphviz.
.PHONY: graphs
graphs:
	dot -Tpng nfa.dot -o nfa.png
	dot -Tpng dfa.dot -o dfa.png
	xdg-open nfa.png &
	xdg-open dfa.png &
